# Generated by Django 5.0.4 on 2024-04-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alunos",
            options={"verbose_name": "Aluno"},
        ),
        migrations.RemoveField(
            model_name="alunos",
            name="descrição_amnamese",
        ),
        migrations.AddField(
            model_name="alunos",
            name="anamnesis",
            field=models.TextField(default="Qual são as suas queixas?", max_length=500),
        ),
        migrations.AddField(
            model_name="alunos",
            name="celular",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="alunos",
            name="cpf",
            field=models.CharField(default="Digite seu CPF", max_length=11),
        ),
        migrations.AddField(
            model_name="alunos",
            name="endereco",
            field=models.CharField(default="Digite o endereço", max_length=100),
        ),
        migrations.AddField(
            model_name="alunos",
            name="gympass",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alunos",
            name="idade",
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name="alunos",
            name="plano_escolhido",
            field=models.CharField(
                choices=[
                    ("1x", "1x na semana"),
                    ("2x", "2x na semana"),
                    ("3x", "3x na semana"),
                ],
                default="1x",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alunos",
            name="sobrenome",
            field=models.CharField(default="Digite o Sobrenome", max_length=30),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="data_inicio",
            field=models.DateField(default="Escolha a data de inicio"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="data_pagamento",
            field=models.DateField(default="Escolha um data de pagamento"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="nome",
            field=models.CharField(default="Digite o nome", max_length=30),
        ),
    ]
