# Generated by Django 5.0.4 on 2024-05-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0002_alter_alunos_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alunos",
            name="data_inicio",
            field=models.DateTimeField(default="Escolha a data de inicio"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="data_pagamento",
            field=models.DateTimeField(default="Escolha um data de pagamento"),
        ),
    ]
