# Generated by Django 5.0.4 on 2024-05-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0002_alter_alunos_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alunos",
            name="idade",
            field=models.IntegerField(default=18),
        ),
    ]
