# Generated by Django 5.0.4 on 2024-05-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0003_alter_alunos_data_inicio_alter_alunos_data_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alunos",
            name="data_inicio",
            field=models.DateField(default="Escolha a data de inicio"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="data_pagamento",
            field=models.DateField(default="Escolha um data de pagamento"),
        ),
    ]
